CREATE TABLE Person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    age int,
    email varchar(100)
);
INSERT INTO Person(name, age, email) VALUES ('Tom', 25, 'tom@gamil.com');
INSERT INTO Person(name, age, email) VALUES ('Bob', 54, 'bob@gmail.com');
INSERT INTO Person(name, age, email) VALUES ('Katy', 43, 'katy@gmail.com');